const backdrop=document.getElementById('sheetBackdrop'),content=document.getElementById('sheetContent');
function openSheet(html){content.innerHTML=html;backdrop.classList.add('open');document.getElementById('sheet').scrollTop=0}
function closeSheet(){backdrop.classList.remove('open')}
backdrop.onclick=e=>{if(e.target===backdrop)closeSheet()};
function openDateSheet(periodId=null){
  const active=activePeriod(),last=[...state.periods].sort((a,b)=>a.start.localeCompare(b.start)).at(-1),p=periodId?state.periods.find(x=>x.id===periodId):(active||last);
  openSheet(`<h2>Change period dates</h2><p>Corrections stay on this device and immediately update predictions. Overlapping cycles are not allowed.</p><div class="group"><div class="row"><div class="label"><strong>Start date</strong></div><input id="startInput" type="date" value="${p?.start||todayISO()}"></div><div class="row"><div class="label"><strong>End date</strong><small>Leave empty while active</small></div><input id="endInput" type="date" value="${p?.end||''}"></div></div><button class="primary" id="saveDates">Save dates</button><button class="secondary" id="yesterdayStart" style="width:100%;margin-top:10px">Started yesterday</button>`);
  document.getElementById('saveDates').onclick=()=>{const s=document.getElementById('startInput').value,e=document.getElementById('endInput').value;if(!s)return;if(e&&e<s){alert('End date cannot be before the start date.');return}const conflict=findOverlap(s,e||null,p?.id||null);if(conflict){alert(`These dates overlap the cycle starting ${conflict.start}. Choose non-overlapping dates or adjust the existing cycle dates first.`);return}const old=JSON.stringify(state.periods);if(p){p.start=s;p.end=e||null}else state.periods.push({id:uid(),start:s,end:e||null,source:'manual'});setUndo('Dates updated',()=>{state.periods=JSON.parse(old);save()});save();closeSheet()};
  document.getElementById('yesterdayStart').onclick=()=>{document.getElementById('startInput').value=iso(addDays(new Date(),-1))};
}
function openFlowSheet(di=todayISO()){
  const current=state.flows[di]||'';openSheet(`<h2>${di===todayISO()?'Today’s flow':'Bleeding / flow'}</h2><p>${fmtLong.format(parse(di))} · Optional. This never blocks period logging.</p><div class="flow-pills">${['Spotting','Light','Medium','Heavy'].map(v=>`<button data-flow="${v}" class="${current===v?'active':''}">${v}${current===v?' ✓':''}</button>`).join('')}</div>${current?'<button class="secondary danger" id="clearFlow" style="width:100%">Clear flow</button>':''}`);
  document.querySelectorAll('[data-flow]').forEach(b=>b.onclick=()=>{const old=state.flows[di];state.flows[di]=b.dataset.flow;setUndo('Flow updated',()=>{if(old)state.flows[di]=old;else delete state.flows[di];save()});save();closeSheet()});const clear=document.getElementById('clearFlow');if(clear)clear.onclick=()=>{const old=state.flows[di];delete state.flows[di];setUndo('Flow cleared',()=>{if(old)state.flows[di]=old;save()});save();closeSheet()};
}
function openNoteSheet(di){const n=state.notes[di]||'';openSheet(`<h2>Private note</h2><p>${fmtLong.format(parse(di))}</p><textarea id="noteInput" placeholder="Add context for yourself or a future appointment…">${escapeHtml(n)}</textarea><button class="primary" id="saveNote">Save note</button>${n?'<button class="secondary danger" id="deleteNote" style="width:100%;margin-top:10px">Delete note</button>':''}`);document.getElementById('saveNote').onclick=()=>{const value=document.getElementById('noteInput').value.trim();if(value)state.notes[di]=value;else delete state.notes[di];save();closeSheet()};const del=document.getElementById('deleteNote');if(del)del.onclick=()=>{const old=state.notes[di];delete state.notes[di];setUndo('Note removed',()=>{if(old)state.notes[di]=old;save()});save();closeSheet()}}
function deleteDayDetails(di){const had=Boolean(state.symptoms[di]||state.flows[di]||state.notes[di]);if(!had)return;if(confirm(`Remove symptoms, flow and note recorded for ${fmtLong.format(parse(di))}?`)){const oldSymptoms=state.symptoms[di]?clone(state.symptoms[di]):null,oldFlow=state.flows[di],oldNote=state.notes[di];delete state.symptoms[di];delete state.flows[di];delete state.notes[di];setUndo('Day details removed',()=>{if(oldSymptoms)state.symptoms[di]=oldSymptoms;else delete state.symptoms[di];if(oldFlow)state.flows[di]=oldFlow;else delete state.flows[di];if(oldNote)state.notes[di]=oldNote;else delete state.notes[di];save()});save();closeSheet()}}
function openCycleSheet(id){const p=state.periods.find(x=>x.id===id);if(!p)return;openSheet(`<h2>Cycle starting ${fmtShort.format(parse(p.start))}</h2><p>${p.end?`Confirmed from ${p.start} to ${p.end} · ${daysBetween(p.start,p.end)+1} days.`:`Active cycle beginning ${p.start}.`}</p><div class="action-stack"><button class="primary" id="editCycleDates">Edit dates</button></div><p class="smallprint">Confirmed cycles are corrected by editing their dates rather than deleting the cycle.</p>`);document.getElementById('editCycleDates').onclick=()=>{closeSheet();openDateSheet(id)}}
function openCustomSymptomSheet(di){
  const existing=customSymptomsForDate(di);openSheet(`<h2>Add another symptom</h2><p>${fmtLong.format(parse(di))}</p><input class="field" id="customSymptomName" type="text" placeholder="e.g. cramps, dizziness"><div class="group">${[1,2,3].map(level=>`<button class="row" data-custom-level="${level}" style="width:100%;background:transparent"><span>${severity[level]}</span><span>›</span></button>`).join('')}</div>${existing.length?`<div class="custom-symptom-list"><p class="smallprint">Already logged</p>${existing.map(([id,level])=>`<div class="row"><div class="label"><strong>${escapeHtml(symptomLabel(id))}</strong><small>${severity[level]}</small></div><button data-delete-custom="${escapeHtml(id)}">Remove</button></div>`).join('')}</div>`:''}`);
  document.querySelectorAll('[data-custom-level]').forEach(b=>b.onclick=()=>{const name=document.getElementById('customSymptomName').value.trim();if(!name){alert('Enter a symptom name first.');return}setSymptomLevel(di,`custom:${name}`,Number(b.dataset.customLevel));openSymptomsForDate(di)});document.querySelectorAll('[data-delete-custom]').forEach(b=>b.onclick=()=>{setSymptomLevel(di,b.dataset.deleteCustom,0);openCustomSymptomSheet(di)});
}
function openSymptomsForDate(di){
  openSheet(`<h2>Symptoms</h2><p>${fmtLong.format(parse(di))}</p><div class="date-symptom-grid" id="dateSymptomGrid"></div><button class="secondary" id="backToDay" style="width:100%;margin-top:8px">Back to day</button>`);const grid=document.getElementById('dateSymptomGrid');symptoms.forEach(([id,label])=>grid.appendChild(makeSymptomButton(di,id,label)));document.getElementById('backToDay').onclick=()=>openDaySheet(di);
}
function openDaySheet(di){
  const p=state.periods.find(p=>di>=p.start&&di<=(p.end||todayISO())),sym=state.symptoms[di]||{},flow=state.flows[di],note=state.notes[di],hasDetails=Boolean(Object.keys(sym).length||flow||note),pain=painLevelForDate(di);
  const symptomText=Object.entries(sym).map(([id,level])=>`${symptomLabel(id)}: ${severity[level]}`).join(', ');
  openSheet(`<h2>${fmtLong.format(parse(di))}</h2><p>${p?'Confirmed period day':predictedOn(di)?'Predicted period day':'No period recorded'}${pain?` · ${severity[pain]} pain`:''}</p><div class="group"><div class="row"><div class="label"><strong>Bleeding / flow</strong></div><span>${flow||'Not logged'}</span></div><div class="row"><div class="label"><strong>Symptoms</strong><small>${escapeHtml(symptomText||'No symptoms recorded')}</small></div><span>${Object.keys(sym).length||'None'}</span></div><div class="row"><div class="label"><strong>Note</strong></div><span>${note?'Added':'None'}</span></div></div><div class="action-stack"><button class="primary" id="editDaySymptoms">Add or edit symptoms</button><button class="secondary" id="editDayFlow">Change bleeding / flow</button><button class="secondary" id="editDayNote">Add or edit note</button>${hasDetails?'<button class="secondary danger" id="deleteDayDetailsBtn">Remove day details</button>':''}</div>`);
  document.getElementById('editDaySymptoms').onclick=()=>openSymptomsForDate(di);document.getElementById('editDayFlow').onclick=()=>openFlowSheet(di);document.getElementById('editDayNote').onclick=()=>openNoteSheet(di);const delDetails=document.getElementById('deleteDayDetailsBtn');if(delDetails)delDetails.onclick=()=>deleteDayDetails(di);
}

function openSettings(){
  openSheet(`<h2>Settings</h2><div class="warning"><div>⌁</div><div><strong>Your information stays on this device</strong><p>If you lose this phone, delete the app or clear browser data, your history may be lost. Save an encrypted backup regularly.</p></div></div><div class="group"><div class="row"><div class="label"><strong>Typical cycle</strong></div><input id="cycleLengthInput" type="number" min="15" max="60" value="${state.profile.typicalCycleLength}"></div><div class="row"><div class="label"><strong>Typical period</strong></div><input id="periodLengthInput" type="number" min="1" max="14" value="${state.profile.typicalPeriodDuration}"></div></div><div class="group"><button class="row" id="backupBtn" style="width:100%;background:transparent"><div class="label"><strong>Create encrypted backup</strong><small>${state.lastBackup?'Last backup '+state.lastBackup:'No backup yet'}</small></div><span class="disclosure">›</span></button><button class="row" id="csvBtn" style="width:100%;background:transparent"><div class="label"><strong>Export CSV</strong><small>Dates, flow, symptoms and notes</small></div><span class="disclosure">›</span></button><button class="row" id="restoreBtn" style="width:100%;background:transparent"><div class="label"><strong>Import or restore</strong><small>CSV, encrypted backup, or legacy JSON</small></div><span class="disclosure">›</span></button></div><div class="group"><button class="row danger" id="resetBtn" style="width:100%;background:transparent"><span>Reset prototype data</span><span>›</span></button></div><p class="smallprint">No account, server, cloud sync, advertising or analytics is used in this prototype. Data is stored in this browser’s local storage on this device. The developer receives no copy.</p>`);
  document.getElementById('cycleLengthInput').onchange=e=>{state.profile.typicalCycleLength=Number(e.target.value)||28;save()};
  document.getElementById('periodLengthInput').onchange=e=>{state.profile.typicalPeriodDuration=Number(e.target.value)||5;save()};
  document.getElementById('backupBtn').onclick=openBackupSheet;document.getElementById('csvBtn').onclick=exportCSV;document.getElementById('restoreBtn').onclick=()=>document.getElementById('importInput').click();
  document.getElementById('resetBtn').onclick=()=>{if(confirm('Reset all prototype data stored in this browser? Create a backup first if you may need it later.')){localStorage.removeItem(KEY);state=defaultState();save();closeSheet()}};
}
document.getElementById('settingsBtn').onclick=openSettings;
